package com.ebeijia.mapper;

import com.ebeijia.models.UsrRoleacc;
import com.ebeijia.models.UsrRoleaccKey;

public interface UsrRoleaccMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_roleacc
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int deleteByPrimaryKey(UsrRoleaccKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_roleacc
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insert(UsrRoleacc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_roleacc
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insertSelective(UsrRoleacc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_roleacc
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    UsrRoleacc selectByPrimaryKey(UsrRoleaccKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_roleacc
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKeySelective(UsrRoleacc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_roleacc
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKey(UsrRoleacc record);
}