package com.ebeijia.mapper;

import com.ebeijia.models.UsrRole;

public interface UsrRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_role
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_role
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insert(UsrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_role
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insertSelective(UsrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_role
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    UsrRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_role
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKeySelective(UsrRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_role
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKey(UsrRole record);
}