package com.ebeijia.mapper;

import com.ebeijia.models.UsrUserinfo;

public interface UsrUserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_userinfo
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_userinfo
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insert(UsrUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_userinfo
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insertSelective(UsrUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_userinfo
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    UsrUserinfo selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_userinfo
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKeySelective(UsrUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_userinfo
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(UsrUserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_userinfo
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKey(UsrUserinfo record);
}