package com.ebeijia.mapper;

import com.ebeijia.models.UsrUser;

public interface UsrUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_user
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_user
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insert(UsrUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_user
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insertSelective(UsrUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_user
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    UsrUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_user
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKeySelective(UsrUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usr_user
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKey(UsrUser record);
}