package com.ebeijia.mapper;

import org.apache.ibatis.annotations.Param;

import com.ebeijia.models.VerChannel;

public interface VerChannelMapper {
  
	int selectByChnlId(@Param("chnlId") String chnlId);
	
	VerChannel selectVerChannelByChnlId(@Param("chnlId") String chnlId);
	
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_channel
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insert(VerChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_channel
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insertSelective(VerChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_channel
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    VerChannel selectByPrimaryKey(Integer chnlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_channel
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKeySelective(VerChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_channel
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(VerChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_channel
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKey(VerChannel record);
}