package com.ebeijia.mapper;

import java.util.List;

import com.ebeijia.models.VerSofttype;

public interface VerSofttypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_softtype
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_softtype
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insert(VerSofttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_softtype
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insertSelective(VerSofttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_softtype
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    VerSofttype selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_softtype
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKeySelective(VerSofttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_softtype
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(VerSofttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_softtype
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKey(VerSofttype record);
    
    List<VerSofttype> selectAllResult();
    
}