package com.ebeijia.mapper;

import com.ebeijia.models.VerSoftimg;

public interface VerSoftimgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_softimg
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_softimg
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insert(VerSoftimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_softimg
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int insertSelective(VerSoftimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_softimg
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    VerSoftimg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_softimg
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKeySelective(VerSoftimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ver_softimg
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    int updateByPrimaryKey(VerSoftimg record);
}