package com.ebeijia.models;

import java.util.Date;

public class MdiFileinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mdi_fileinfo.FILE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mdi_fileinfo.FILE_NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mdi_fileinfo.URL_PATH
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String urlPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mdi_fileinfo.STATE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mdi_fileinfo.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mdi_fileinfo.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mdi_fileinfo.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mdi_fileinfo.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mdi_fileinfo.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Date lastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mdi_fileinfo.FILE_ID
     *
     * @return the value of mdi_fileinfo.FILE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mdi_fileinfo.FILE_ID
     *
     * @param fileId the value for mdi_fileinfo.FILE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mdi_fileinfo.FILE_NAME
     *
     * @return the value of mdi_fileinfo.FILE_NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mdi_fileinfo.FILE_NAME
     *
     * @param fileName the value for mdi_fileinfo.FILE_NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mdi_fileinfo.URL_PATH
     *
     * @return the value of mdi_fileinfo.URL_PATH
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getUrlPath() {
        return urlPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mdi_fileinfo.URL_PATH
     *
     * @param urlPath the value for mdi_fileinfo.URL_PATH
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setUrlPath(String urlPath) {
        this.urlPath = urlPath == null ? null : urlPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mdi_fileinfo.STATE
     *
     * @return the value of mdi_fileinfo.STATE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mdi_fileinfo.STATE
     *
     * @param state the value for mdi_fileinfo.STATE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mdi_fileinfo.RES1
     *
     * @return the value of mdi_fileinfo.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes1() {
        return res1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mdi_fileinfo.RES1
     *
     * @param res1 the value for mdi_fileinfo.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes1(String res1) {
        this.res1 = res1 == null ? null : res1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mdi_fileinfo.RES2
     *
     * @return the value of mdi_fileinfo.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes2() {
        return res2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mdi_fileinfo.RES2
     *
     * @param res2 the value for mdi_fileinfo.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes2(String res2) {
        this.res2 = res2 == null ? null : res2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mdi_fileinfo.RES3
     *
     * @return the value of mdi_fileinfo.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes3() {
        return res3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mdi_fileinfo.RES3
     *
     * @param res3 the value for mdi_fileinfo.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes3(String res3) {
        this.res3 = res3 == null ? null : res3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mdi_fileinfo.RES4
     *
     * @return the value of mdi_fileinfo.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes4() {
        return res4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mdi_fileinfo.RES4
     *
     * @param res4 the value for mdi_fileinfo.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes4(String res4) {
        this.res4 = res4 == null ? null : res4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mdi_fileinfo.LAST_TIME
     *
     * @return the value of mdi_fileinfo.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mdi_fileinfo.LAST_TIME
     *
     * @param lastTime the value for mdi_fileinfo.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

}