package com.ebeijia.models;

public class UsrLogininfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.USER_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.TYPE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.USER_ID
     *
     * @return the value of usr_logininfo.USER_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.USER_ID
     *
     * @param userId the value for usr_logininfo.USER_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.TYPE
     *
     * @return the value of usr_logininfo.TYPE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.TYPE
     *
     * @param type the value for usr_logininfo.TYPE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}