package com.ebeijia.models;

import java.util.Date;

public class UsrLogininfo extends UsrLogininfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.SER_KEY
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String serKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.AUTH_TOKEN
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String authToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.DEV_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String devId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.IS_LOGGED
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String isLogged;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.LAST_LOGOUT_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Date lastLogoutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.LAST_LOGIN_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.RES5
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.RES6
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_logininfo.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Date lastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.SER_KEY
     *
     * @return the value of usr_logininfo.SER_KEY
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getSerKey() {
        return serKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.SER_KEY
     *
     * @param serKey the value for usr_logininfo.SER_KEY
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setSerKey(String serKey) {
        this.serKey = serKey == null ? null : serKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.AUTH_TOKEN
     *
     * @return the value of usr_logininfo.AUTH_TOKEN
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getAuthToken() {
        return authToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.AUTH_TOKEN
     *
     * @param authToken the value for usr_logininfo.AUTH_TOKEN
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setAuthToken(String authToken) {
        this.authToken = authToken == null ? null : authToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.DEV_ID
     *
     * @return the value of usr_logininfo.DEV_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getDevId() {
        return devId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.DEV_ID
     *
     * @param devId the value for usr_logininfo.DEV_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setDevId(String devId) {
        this.devId = devId == null ? null : devId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.IS_LOGGED
     *
     * @return the value of usr_logininfo.IS_LOGGED
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getIsLogged() {
        return isLogged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.IS_LOGGED
     *
     * @param isLogged the value for usr_logininfo.IS_LOGGED
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setIsLogged(String isLogged) {
        this.isLogged = isLogged == null ? null : isLogged.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.LAST_LOGOUT_TIME
     *
     * @return the value of usr_logininfo.LAST_LOGOUT_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Date getLastLogoutTime() {
        return lastLogoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.LAST_LOGOUT_TIME
     *
     * @param lastLogoutTime the value for usr_logininfo.LAST_LOGOUT_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setLastLogoutTime(Date lastLogoutTime) {
        this.lastLogoutTime = lastLogoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.LAST_LOGIN_TIME
     *
     * @return the value of usr_logininfo.LAST_LOGIN_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for usr_logininfo.LAST_LOGIN_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.RES1
     *
     * @return the value of usr_logininfo.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes1() {
        return res1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.RES1
     *
     * @param res1 the value for usr_logininfo.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes1(String res1) {
        this.res1 = res1 == null ? null : res1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.RES2
     *
     * @return the value of usr_logininfo.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes2() {
        return res2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.RES2
     *
     * @param res2 the value for usr_logininfo.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes2(String res2) {
        this.res2 = res2 == null ? null : res2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.RES3
     *
     * @return the value of usr_logininfo.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes3() {
        return res3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.RES3
     *
     * @param res3 the value for usr_logininfo.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes3(String res3) {
        this.res3 = res3 == null ? null : res3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.RES4
     *
     * @return the value of usr_logininfo.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes4() {
        return res4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.RES4
     *
     * @param res4 the value for usr_logininfo.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes4(String res4) {
        this.res4 = res4 == null ? null : res4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.RES5
     *
     * @return the value of usr_logininfo.RES5
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes5() {
        return res5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.RES5
     *
     * @param res5 the value for usr_logininfo.RES5
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes5(String res5) {
        this.res5 = res5 == null ? null : res5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.RES6
     *
     * @return the value of usr_logininfo.RES6
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes6() {
        return res6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.RES6
     *
     * @param res6 the value for usr_logininfo.RES6
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes6(String res6) {
        this.res6 = res6 == null ? null : res6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_logininfo.LAST_TIME
     *
     * @return the value of usr_logininfo.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_logininfo.LAST_TIME
     *
     * @param lastTime the value for usr_logininfo.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
}