package com.ebeijia.models;

public class UsrRoleaccKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_roleacc.ROLE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_roleacc.ACC_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String accId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_roleacc.ROLE_ID
     *
     * @return the value of usr_roleacc.ROLE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_roleacc.ROLE_ID
     *
     * @param roleId the value for usr_roleacc.ROLE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_roleacc.ACC_ID
     *
     * @return the value of usr_roleacc.ACC_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getAccId() {
        return accId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_roleacc.ACC_ID
     *
     * @param accId the value for usr_roleacc.ACC_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setAccId(String accId) {
        this.accId = accId == null ? null : accId.trim();
    }
}