package com.ebeijia.models;

import java.util.Date;

public class UsrRoleacc extends UsrRoleaccKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_roleacc.ACC_NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String accName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_roleacc.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Date lastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_roleacc.ACC_NAME
     *
     * @return the value of usr_roleacc.ACC_NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getAccName() {
        return accName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_roleacc.ACC_NAME
     *
     * @param accName the value for usr_roleacc.ACC_NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setAccName(String accName) {
        this.accName = accName == null ? null : accName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_roleacc.LAST_TIME
     *
     * @return the value of usr_roleacc.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_roleacc.LAST_TIME
     *
     * @param lastTime the value for usr_roleacc.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
}