package com.ebeijia.models;

import java.util.Date;

public class UsrRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_role.ROLE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_role.NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_role.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Date lastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_role.ROLE_ID
     *
     * @return the value of usr_role.ROLE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_role.ROLE_ID
     *
     * @param roleId the value for usr_role.ROLE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_role.NAME
     *
     * @return the value of usr_role.NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_role.NAME
     *
     * @param name the value for usr_role.NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_role.LAST_TIME
     *
     * @return the value of usr_role.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_role.LAST_TIME
     *
     * @param lastTime the value for usr_role.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
}