package com.ebeijia.models;

import java.util.Date;

public class UsrUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.USER_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.ROLE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.REG_TYPE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String regType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.PWD
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.STATE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.RES5
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.RES6
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_user.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Date lastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.USER_ID
     *
     * @return the value of usr_user.USER_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.USER_ID
     *
     * @param userId the value for usr_user.USER_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.ROLE_ID
     *
     * @return the value of usr_user.ROLE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.ROLE_ID
     *
     * @param roleId the value for usr_user.ROLE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.REG_TYPE
     *
     * @return the value of usr_user.REG_TYPE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRegType() {
        return regType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.REG_TYPE
     *
     * @param regType the value for usr_user.REG_TYPE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRegType(String regType) {
        this.regType = regType == null ? null : regType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.PWD
     *
     * @return the value of usr_user.PWD
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.PWD
     *
     * @param pwd the value for usr_user.PWD
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.STATE
     *
     * @return the value of usr_user.STATE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.STATE
     *
     * @param state the value for usr_user.STATE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.RES1
     *
     * @return the value of usr_user.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes1() {
        return res1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.RES1
     *
     * @param res1 the value for usr_user.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes1(String res1) {
        this.res1 = res1 == null ? null : res1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.RES2
     *
     * @return the value of usr_user.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes2() {
        return res2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.RES2
     *
     * @param res2 the value for usr_user.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes2(String res2) {
        this.res2 = res2 == null ? null : res2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.RES3
     *
     * @return the value of usr_user.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes3() {
        return res3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.RES3
     *
     * @param res3 the value for usr_user.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes3(String res3) {
        this.res3 = res3 == null ? null : res3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.RES4
     *
     * @return the value of usr_user.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes4() {
        return res4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.RES4
     *
     * @param res4 the value for usr_user.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes4(String res4) {
        this.res4 = res4 == null ? null : res4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.RES5
     *
     * @return the value of usr_user.RES5
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes5() {
        return res5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.RES5
     *
     * @param res5 the value for usr_user.RES5
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes5(String res5) {
        this.res5 = res5 == null ? null : res5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.RES6
     *
     * @return the value of usr_user.RES6
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes6() {
        return res6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.RES6
     *
     * @param res6 the value for usr_user.RES6
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes6(String res6) {
        this.res6 = res6 == null ? null : res6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_user.LAST_TIME
     *
     * @return the value of usr_user.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_user.LAST_TIME
     *
     * @param lastTime the value for usr_user.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
}