package com.ebeijia.models;

import java.util.Date;

public class UsrUserinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.USER_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.USER_TYPE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.SEX
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.MOBILE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.EMAIL
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.ORG_NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.ORG_TEL
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String orgTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.RES5
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.RES6
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usr_userinfo.ABOUT
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String about;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.USER_ID
     *
     * @return the value of usr_userinfo.USER_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.USER_ID
     *
     * @param userId the value for usr_userinfo.USER_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.USER_TYPE
     *
     * @return the value of usr_userinfo.USER_TYPE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.USER_TYPE
     *
     * @param userType the value for usr_userinfo.USER_TYPE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.NAME
     *
     * @return the value of usr_userinfo.NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.NAME
     *
     * @param name the value for usr_userinfo.NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.SEX
     *
     * @return the value of usr_userinfo.SEX
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.SEX
     *
     * @param sex the value for usr_userinfo.SEX
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.MOBILE
     *
     * @return the value of usr_userinfo.MOBILE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.MOBILE
     *
     * @param mobile the value for usr_userinfo.MOBILE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.EMAIL
     *
     * @return the value of usr_userinfo.EMAIL
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.EMAIL
     *
     * @param email the value for usr_userinfo.EMAIL
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.ORG_NAME
     *
     * @return the value of usr_userinfo.ORG_NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.ORG_NAME
     *
     * @param orgName the value for usr_userinfo.ORG_NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.ORG_TEL
     *
     * @return the value of usr_userinfo.ORG_TEL
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getOrgTel() {
        return orgTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.ORG_TEL
     *
     * @param orgTel the value for usr_userinfo.ORG_TEL
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setOrgTel(String orgTel) {
        this.orgTel = orgTel == null ? null : orgTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.RES3
     *
     * @return the value of usr_userinfo.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes3() {
        return res3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.RES3
     *
     * @param res3 the value for usr_userinfo.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes3(String res3) {
        this.res3 = res3 == null ? null : res3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.RES4
     *
     * @return the value of usr_userinfo.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes4() {
        return res4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.RES4
     *
     * @param res4 the value for usr_userinfo.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes4(String res4) {
        this.res4 = res4 == null ? null : res4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.RES5
     *
     * @return the value of usr_userinfo.RES5
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes5() {
        return res5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.RES5
     *
     * @param res5 the value for usr_userinfo.RES5
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes5(String res5) {
        this.res5 = res5 == null ? null : res5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.RES6
     *
     * @return the value of usr_userinfo.RES6
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes6() {
        return res6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.RES6
     *
     * @param res6 the value for usr_userinfo.RES6
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes6(String res6) {
        this.res6 = res6 == null ? null : res6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.LAST_TIME
     *
     * @return the value of usr_userinfo.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.LAST_TIME
     *
     * @param lastTime the value for usr_userinfo.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usr_userinfo.ABOUT
     *
     * @return the value of usr_userinfo.ABOUT
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getAbout() {
        return about;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usr_userinfo.ABOUT
     *
     * @param about the value for usr_userinfo.ABOUT
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setAbout(String about) {
        this.about = about == null ? null : about.trim();
    }
}