package com.ebeijia.models;

import java.util.Date;

public class VerChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_channel.ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_channel.CHNL_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String chnlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_channel.NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_channel.STATE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_channel.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_channel.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_channel.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_channel.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_channel.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_channel.ABOUT
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String about;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_channel.ID
     *
     * @return the value of ver_channel.ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_channel.ID
     *
     * @param id the value for ver_channel.ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_channel.CHNL_ID
     *
     * @return the value of ver_channel.CHNL_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getChnlId() {
        return chnlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_channel.CHNL_ID
     *
     * @param chnlId the value for ver_channel.CHNL_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setChnlId(String chnlId) {
        this.chnlId = chnlId == null ? null : chnlId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_channel.NAME
     *
     * @return the value of ver_channel.NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_channel.NAME
     *
     * @param name the value for ver_channel.NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_channel.STATE
     *
     * @return the value of ver_channel.STATE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_channel.STATE
     *
     * @param state the value for ver_channel.STATE
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_channel.RES1
     *
     * @return the value of ver_channel.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes1() {
        return res1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_channel.RES1
     *
     * @param res1 the value for ver_channel.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes1(String res1) {
        this.res1 = res1 == null ? null : res1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_channel.RES2
     *
     * @return the value of ver_channel.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes2() {
        return res2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_channel.RES2
     *
     * @param res2 the value for ver_channel.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes2(String res2) {
        this.res2 = res2 == null ? null : res2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_channel.RES3
     *
     * @return the value of ver_channel.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes3() {
        return res3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_channel.RES3
     *
     * @param res3 the value for ver_channel.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes3(String res3) {
        this.res3 = res3 == null ? null : res3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_channel.RES4
     *
     * @return the value of ver_channel.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes4() {
        return res4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_channel.RES4
     *
     * @param res4 the value for ver_channel.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes4(String res4) {
        this.res4 = res4 == null ? null : res4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_channel.LAST_TIME
     *
     * @return the value of ver_channel.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_channel.LAST_TIME
     *
     * @param lastTime the value for ver_channel.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_channel.ABOUT
     *
     * @return the value of ver_channel.ABOUT
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getAbout() {
        return about;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_channel.ABOUT
     *
     * @param about the value for ver_channel.ABOUT
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setAbout(String about) {
        this.about = about == null ? null : about.trim();
    }
}