package com.ebeijia.models;

import java.util.Date;

public class VerSofttype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softtype.TYPE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softtype.NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softtype.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softtype.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softtype.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softtype.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softtype.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softtype.ABOUT
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String about;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softtype.TYPE_ID
     *
     * @return the value of ver_softtype.TYPE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softtype.TYPE_ID
     *
     * @param typeId the value for ver_softtype.TYPE_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softtype.NAME
     *
     * @return the value of ver_softtype.NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softtype.NAME
     *
     * @param name the value for ver_softtype.NAME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softtype.RES1
     *
     * @return the value of ver_softtype.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes1() {
        return res1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softtype.RES1
     *
     * @param res1 the value for ver_softtype.RES1
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes1(String res1) {
        this.res1 = res1 == null ? null : res1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softtype.RES2
     *
     * @return the value of ver_softtype.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes2() {
        return res2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softtype.RES2
     *
     * @param res2 the value for ver_softtype.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes2(String res2) {
        this.res2 = res2 == null ? null : res2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softtype.RES3
     *
     * @return the value of ver_softtype.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes3() {
        return res3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softtype.RES3
     *
     * @param res3 the value for ver_softtype.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes3(String res3) {
        this.res3 = res3 == null ? null : res3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softtype.RES4
     *
     * @return the value of ver_softtype.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes4() {
        return res4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softtype.RES4
     *
     * @param res4 the value for ver_softtype.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes4(String res4) {
        this.res4 = res4 == null ? null : res4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softtype.LAST_TIME
     *
     * @return the value of ver_softtype.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softtype.LAST_TIME
     *
     * @param lastTime the value for ver_softtype.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softtype.ABOUT
     *
     * @return the value of ver_softtype.ABOUT
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getAbout() {
        return about;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softtype.ABOUT
     *
     * @param about the value for ver_softtype.ABOUT
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setAbout(String about) {
        this.about = about == null ? null : about.trim();
    }
}