package com.ebeijia.models;

import java.util.Date;

public class VerSoftimg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softimg.ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softimg.SOFT_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Integer softId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softimg.IMG_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Integer imgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softimg.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softimg.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softimg.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private String res4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ver_softimg.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    private Date lastTime;
    
    private MdiFileinfo mdiFileinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softimg.ID
     *
     * @return the value of ver_softimg.ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softimg.ID
     *
     * @param id the value for ver_softimg.ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softimg.SOFT_ID
     *
     * @return the value of ver_softimg.SOFT_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Integer getSoftId() {
        return softId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softimg.SOFT_ID
     *
     * @param softId the value for ver_softimg.SOFT_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setSoftId(Integer softId) {
        this.softId = softId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softimg.IMG_ID
     *
     * @return the value of ver_softimg.IMG_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softimg.IMG_ID
     *
     * @param imgId the value for ver_softimg.IMG_ID
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softimg.RES2
     *
     * @return the value of ver_softimg.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes2() {
        return res2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softimg.RES2
     *
     * @param res2 the value for ver_softimg.RES2
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes2(String res2) {
        this.res2 = res2 == null ? null : res2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softimg.RES3
     *
     * @return the value of ver_softimg.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes3() {
        return res3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softimg.RES3
     *
     * @param res3 the value for ver_softimg.RES3
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes3(String res3) {
        this.res3 = res3 == null ? null : res3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softimg.RES4
     *
     * @return the value of ver_softimg.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public String getRes4() {
        return res4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softimg.RES4
     *
     * @param res4 the value for ver_softimg.RES4
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setRes4(String res4) {
        this.res4 = res4 == null ? null : res4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ver_softimg.LAST_TIME
     *
     * @return the value of ver_softimg.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ver_softimg.LAST_TIME
     *
     * @param lastTime the value for ver_softimg.LAST_TIME
     *
     * @mbggenerated Fri Oct 14 17:02:13 CST 2016
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }
    
}